openapi: 3.0.1
info:
  title: Todos
  version: 0.1.0
servers:
- url: "{server}:{port}/todos"
  variables:
    server:
      default: http://localhost
    port:
      default: "7080"
paths:
  /:
    get:
      summary: Returns all Todo items with optionally filtered from the done status.
      operationId: get
      parameters:
      - name: done
        in: query
        description: Optional filter to list the Todo items by done status.
        schema:
          type: boolean
          nullable: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Add a Todo item.
      operationId: post
      requestBody:
        description: User input for the new Todo item.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoInput'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /{id}:
    get:
      summary: Returns a Todo item from a given Id.
      operationId: getId
      parameters:
      - name: id
        in: path
        description: Id of the required Todo item.
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    put:
      summary: Update the done state of a Todo item.
      operationId: putId
      parameters:
      - name: id
        in: path
        description: Id of the updating Todo item.
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Updated todo item.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
components:
  schemas:
    Todo:
      required:
      - done
      - id
      - title
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        done:
          type: boolean
      description: Record that represents Todo item
    CreateTodoInput:
      required:
      - title
      type: object
      properties:
        title:
          type: string
        description:
          type: string
      description: User input record for createTodo GQL mutation
